In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB

In [4]:
df.isnull()

     User ID  Gender    Age  EstimatedSalary  Purchased
0      False   False  False            False      False
1      False   False  False            False      False
2      False   False  False            False      False
3      False   False  False            False      False
4      False   False  False            False      False
5      False   False  False            False      False
6      False   False  False            False      False
7      False   False  False            False      False
8      False   False  False            False      False
9      False   False  False            False      False
10     False   False  False            False      False
11     False   False  False            False      False
12     False   False  False            False      False
13     False   False  False            False      False
14     False   False  False            False      False
15     False   False  False            False      False
16     False   False  False            False      False
17     False   False  False            False      False
18     False   False  False            False      False
19     False   False  False            False      False
20     False   False  False            False      False
21     False   False  False            False      False
22     False   False  False            False      False
23     False   False  False            False      False
24     False   False  False            False      False
25     False   False  False            False      False
26     False   False  False            False      False
27     False   False  False            False      False
28     False   False  False            False      False
29     False   False  False            False      False
..       ...     ...    ...              ...        ...
370    False   False  False            False      False
371    False   False  False            False      False
372    False   False  False            False      False
373    False   False  False            False      False
374    False   False  False            False      False
375    False   False  False            False      False
376    False   False  False            False      False
377    False   False  False            False      False
378    False   False  False            False      False
379    False   False  False            False      False
380    False   False  False            False      False
381    False   False  False            False      False
382    False   False  False            False      False
383    False   False  False            False      False
384    False   False  False            False      False
385    False   False  False            False      False
386    False   False  False            False      False
387    False   False  False            False      False
388    False   False  False            False      False
389    False   False  False            False      False
390    False   False  False            False      False
391    False   False  False            False      False
392    False   False  False            False      False
393    False   False  False            False      False
394    False   False  False            False      False
395    False   False  False            False      False
396    False   False  False            False      False
397    False   False  False            False      False
398    False   False  False            False      False
399    False   False  False            False      False

[400 rows x 5 columns]

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
for column in df.columns:
    print(column+': ', df[column].unique(),'\n' )

User ID:  [15624510 15810944 15668575 15603246 15804002 15728773 15598044 15694829
 15600575 15727311 15570769 15606274 15746139 15704987 15628972 15697686
 15733883 15617482 15704583 15621083 15649487 15736760 15714658 15599081
 15705113 15631159 15792818 15633531 15744529 15669656 15581198 15729054
 15573452 15776733 15724858 15713144 15690188 15689425 15671766 15782806
 15764419 15591915 15772798 15792008 15715541 15639277 15798850 15776348
 15727696 15793813 15694395 15764195 15744919 15671655 15654901 15649136
 15775562 15807481 15642885 15789109 15814004 15673619 15595135 15583681
 15605000 15718071 15679760 15654574 15577178 15595324 15756932 15726358
 15595228 15782530 15592877 15651983 15746737 15774179 15667265 15655123
 15595917 15668385 15709476 15711218 15798659 15663939 15694946 15631912
 15768816 15682268 15684801 15636428 15809823 15699284 15786993 15709441
 15710257 15582492 15575694 15756820 15766289 15593014 15584545 15675949
 15672091 15801658 15706185 15789863 15720943 15697997 15665416 15660200
 15619653 15773447 15739160 15689237 15679297 15591433 15642725 15701962
 15811613 15741049 15724423 15574305 15678168 15697020 15610801 15745232
 15722758 15792102 15675185 15801247 15725660 15638963 15800061 15578006
 15668504 15687491 15610403 15741094 15807909 15666141 15617134 15783029
 15622833 15746422 15750839 15749130 15779862 15767871 15679651 15576219
 15699247 15619087 15605327 15610140 15791174 15602373 15762605 15598840
 15744279 15670619 15599533 15757837 15697574 15578738 15762228 15614827
 15789815 15579781 15587013 15570932 15794661 15581654 15644296 15614420
 15609653 15594577 15584114 15673367 15685576 15774727 15694288 15603319
 15759066 15814816 15724402 15571059 15674206 15715160 15730448 15662067
 15779581 15662901 15689751 15667742 15738448 15680243 15745083 15708228
 15628523 15708196 15735549 15809347 15660866 15766609 15654230 15794566
 15800890 15697424 15724536 15735878 15707596 15657163 15622478 15779529
 15636023 15582066 15666675 15732987 15789432 15663161 15694879 15593715
 15575002 15622171 15795224 15685346 15691808 15721007 15794253 15694453
 15813113 15614187 15619407 15646227 15660541 15753874 15617877 15772073
 15701537 15736228 15780572 15769596 15586996 15722061 15638003 15775590
 15730688 15753102 15810075 15723373 15795298 15584320 15724161 15750056
 15609637 15794493 15569641 15815236 15811177 15680587 15672821 15767681
 15600379 15801336 15721592 15581282 15746203 15583137 15680752 15688172
 15791373 15589449 15692819 15727467 15734312 15764604 15613014 15759684
 15609669 15685536 15750447 15663249 15638646 15734161 15631070 15761950
 15649668 15713912 15586757 15596522 15625395 15760570 15566689 15725794
 15673539 15705298 15675791 15747043 15736397 15678201 15720745 15637593
 15598070 15787550 15603942 15733973 15596761 15652400 15717893 15622585
 15733964 15753861 15747097 15594762 15667417 15684861 15742204 15623502
 15774872 15611191 15674331 15619465 15575247 15695679 15713463 15785170
 15796351 15639576 15693264 15589715 15769902 15587177 15814553 15601550
 15664907 15612465 15810800 15665760 15588080 15776844 15717560 15629739
 15729908 15716781 15646936 15768151 15579212 15721835 15800515 15591279
 15587419 15750335 15699619 15606472 15778368 15671387 15573926 15709183
 15577514 15778830 15768072 15768293 15654456 15807525 15574372 15671249
 15779744 15624755 15611430 15774744 15629885 15708791 15793890 15646091
 15596984 15800215 15577806 15749381 15683758 15670615 15715622 15707634
 15806901 15775335 15724150 15627220 15672330 15668521 15807837 15592570
 15748589 15635893 15757632 15691863 15706071 15654296 15755018 15594041]

Gender:  ['Male' 'Female']

Age:  [19 35 26 27 32 25 20 18 29 47 45 46 48 49 31 21 28 33 30 23 24 22 59 34
 39 38 37 42 40 36 41 58 55 52 60 56 53 50 51 57 44 43 54]

EstimatedSalary:  [ 19000  20000  43000  57000  76000  58000  84000 150000  33000  65000
  80000  52000  86000  18000  82000  25000  26000  28000  29000  22000
  49000  41000  23000  30000  74000 137000  16000  44000  90000  27000
  72000  31000  17000  51000 108000  15000  79000  54000 135000  89000
  32000  83000  55000  48000 117000  87000  66000 120000  63000  68000
 113000 112000  42000  88000  62000 118000  85000  81000  50000 116000
 123000  73000  37000  59000 149000  21000  35000  71000  61000  75000
  53000 107000  96000  45000  47000 100000  38000  69000 148000 115000
  34000  60000  70000  36000  39000 134000 101000 130000 114000 142000
  78000 143000  91000 144000 102000 126000 133000 147000 104000 146000
 122000  97000  95000 131000  77000 125000 106000 141000  93000 138000
 119000 105000  99000 129000  46000  64000 139000]

Purchased:  [0 1]

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [10]:
d = ['Gender']
processdf = df
for i in d:
        processdf[i] = encoder.fit_transform(processdf[i])

In [11]:
processdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null int64
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(5)
memory usage: 15.7 KB

In [12]:

dp = pd.DataFrame(processdf)
dp

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
5    15728773       1   27            58000          0
6    15598044       0   27            84000          0
7    15694829       0   32           150000          1
8    15600575       1   25            33000          0
9    15727311       0   35            65000          0
10   15570769       0   26            80000          0
11   15606274       0   26            52000          0
12   15746139       1   20            86000          0
13   15704987       1   32            18000          0
14   15628972       1   18            82000          0
15   15697686       1   29            80000          0
16   15733883       1   47            25000          1
17   15617482       1   45            26000          1
18   15704583       1   46            28000          1
19   15621083       0   48            29000          1
20   15649487       1   45            22000          1
21   15736760       0   47            49000          1
22   15714658       1   48            41000          1
23   15599081       0   45            22000          1
24   15705113       1   46            23000          1
25   15631159       1   47            20000          1
26   15792818       1   49            28000          1
27   15633531       0   47            30000          1
28   15744529       1   29            43000          0
29   15669656       1   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430       0   60            46000          1
371  15774744       1   60            83000          1
372  15629885       0   39            73000          0
373  15708791       1   59           130000          1
374  15793890       0   37            80000          0
375  15646091       0   46            32000          1
376  15596984       0   46            74000          0
377  15800215       0   42            53000          0
378  15577806       1   41            87000          1
379  15749381       0   58            23000          1
380  15683758       1   42            64000          0
381  15670615       1   48            33000          1
382  15715622       0   44           139000          1
383  15707634       1   49            28000          1
384  15806901       0   57            33000          1
385  15775335       1   56            60000          1
386  15724150       0   49            39000          1
387  15627220       1   39            71000          0
388  15672330       1   47            34000          1
389  15668521       0   48            35000          1
390  15807837       1   48            33000          1
391  15592570       1   47            23000          1
392  15748589       0   45            45000          1
393  15635893       1   60            42000          1
394  15757632       0   39            59000          0
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [13]:
x =dp.iloc[:,1:-1].values
y=dp.iloc[:,-1].values

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit(x_test)

C:\Users\FAKUNLE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\FAKUNLE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\FAKUNLE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [16]:
x_train

array([[ 1.02532046e+00,  1.92295008e+00,  2.14601566e+00],
       [-9.75304830e-01,  2.02016082e+00,  3.78719297e-01],
       [-9.75304830e-01, -1.38221530e+00, -4.32498705e-01],
       [-9.75304830e-01, -1.18779381e+00, -1.01194013e+00],
       [-9.75304830e-01,  1.92295008e+00, -9.25023920e-01],
       [-9.75304830e-01,  3.67578135e-01,  2.91803083e-01],
       [-9.75304830e-01,  1.73156642e-01,  1.46942725e-01],
       [ 1.02532046e+00,  2.02016082e+00,  1.74040666e+00],
       [-9.75304830e-01,  7.56421121e-01, -8.38107706e-01],
       [-9.75304830e-01,  2.70367388e-01, -2.87638347e-01],
       [ 1.02532046e+00,  3.67578135e-01, -1.71750061e-01],
       [-9.75304830e-01, -1.18475597e-01,  2.20395980e+00],
       [-9.75304830e-01, -1.47942605e+00, -6.35303205e-01],
       [ 1.02532046e+00, -1.28500455e+00, -1.06988428e+00],
       [ 1.02532046e+00, -1.38221530e+00,  4.07691369e-01],
       [-9.75304830e-01, -1.09058306e+00,  7.55356227e-01],
       [ 1.02532046e+00, -1.47942605e+00, -2.00722133e-01],
       [ 1.02532046e+00,  9.50842613e-01, -1.06988428e+00],
       [ 1.02532046e+00,  9.50842613e-01,  5.81523798e-01],
       [ 1.02532046e+00,  3.67578135e-01,  9.87132798e-01],
       [-9.75304830e-01,  5.61999628e-01, -8.96051849e-01],
       [ 1.02532046e+00, -6.04529329e-01,  1.45068594e+00],
       [-9.75304830e-01, -2.12648508e-02, -5.77359062e-01],
       [-9.75304830e-01, -6.04529329e-01,  1.88526701e+00],
       [-9.75304830e-01,  1.33968560e+00, -1.41754914e+00],
       [-9.75304830e-01,  1.43689635e+00,  9.87132798e-01],
       [ 1.02532046e+00,  7.59458956e-02, -8.09135634e-01],
       [ 1.02532046e+00, -2.12648508e-02, -2.58666276e-01],
       [-9.75304830e-01, -2.15686344e-01, -5.77359062e-01],
       [-9.75304830e-01, -2.15686344e-01, -2.00722133e-01],
       [-9.75304830e-01, -3.12897090e-01, -1.30166085e+00],
       [ 1.02532046e+00, -3.12897090e-01, -5.77359062e-01],
       [ 1.02532046e+00,  3.67578135e-01,  8.89985821e-02],
       [-9.75304830e-01,  8.53631867e-01, -6.06331134e-01],
       [-9.75304830e-01,  2.02016082e+00, -1.18577256e+00],
       [ 1.02532046e+00,  1.04805336e+00, -1.42777990e-01],
       [-9.75304830e-01,  6.59210374e-01,  1.76937873e+00],
       [-9.75304830e-01, -7.01740076e-01,  5.52551726e-01],
       [-9.75304830e-01,  7.56421121e-01,  3.49747226e-01],
       [-9.75304830e-01,  8.53631867e-01, -5.48386991e-01],
       [ 1.02532046e+00, -1.18779381e+00, -1.59138156e+00],
       [ 1.02532046e+00,  2.11737157e+00,  9.29188655e-01],
       [-9.75304830e-01, -2.12648508e-02,  1.21890937e+00],
       [ 1.02532046e+00,  1.73156642e-01,  1.07404901e+00],
       [-9.75304830e-01,  3.67578135e-01, -4.90442848e-01],
       [ 1.02532046e+00, -3.12897090e-01, -3.16610419e-01],
       [ 1.02532046e+00,  9.50842613e-01, -8.38107706e-01],
       [-9.75304830e-01,  9.50842613e-01,  1.85629494e+00],
       [-9.75304830e-01, -2.12648508e-02,  1.24788144e+00],
       [ 1.02532046e+00, -8.96161568e-01,  2.26190394e+00],
       [-9.75304830e-01, -1.18779381e+00, -1.59138156e+00],
       [ 1.02532046e+00,  2.11737157e+00, -8.09135634e-01],
       [ 1.02532046e+00, -1.38221530e+00, -1.47549328e+00],
       [ 1.02532046e+00,  3.67578135e-01,  2.29087602e+00],
       [-9.75304830e-01,  7.56421121e-01,  7.55356227e-01],
       [ 1.02532046e+00, -9.93372315e-01, -3.16610419e-01],
       [ 1.02532046e+00,  7.59458956e-02,  7.55356227e-01],
       [ 1.02532046e+00, -9.93372315e-01,  5.52551726e-01],
       [ 1.02532046e+00,  2.70367388e-01,  6.00265106e-02],
       [ 1.02532046e+00,  6.59210374e-01, -1.27268878e+00],
       [-9.75304830e-01, -5.07318583e-01, -2.68897039e-02],
       [-9.75304830e-01, -1.77105829e+00,  3.49747226e-01],
       [ 1.02532046e+00, -7.01740076e-01,  1.17970654e-01],
       [ 1.02532046e+00,  3.67578135e-01,  2.91803083e-01],
       [-9.75304830e-01, -3.12897090e-01,  6.00265106e-02],
       [-9.75304830e-01, -5.07318583e-01,  2.29087602e+00],
       [ 1.02532046e+00,  1.73156642e-01,  3.10544391e-02],
       [-9.75304830e-01,  1.24247485e+00,  2.20395980e+00],
       [ 1.02532046e+00,  7.56421121e-01,  2.62831011e-01],
       [ 1.02532046e+00, -3.12897090e-01,  1.46942725e-01],
       [ 1.02532046e+00, -2.12648508e-02, -5.48386991e-01],
       [-9.75304830e-01, -2.15686344e-01,  1.46942725e-01],
       [-9.75304830e-01, -1.18475597e-01,  2.33858940e-01],
       [ 1.02532046e+00, -2.12648508e-02, -2.58666276e-01],
       [-9.75304830e-01,  2.11737157e+00,  1.10302108e+00],
       [-9.75304830e-01, -1.77105829e+00,  3.49747226e-01],
       [ 1.02532046e+00,  1.82573933e+00,  1.17970654e-01],
       [ 1.02532046e+00,  3.67578135e-01, -1.42777990e-01],
       [ 1.02532046e+00, -1.18779381e+00,  2.91803083e-01],
       [ 1.02532046e+00,  7.56421121e-01,  1.36376973e+00],
       [ 1.02532046e+00, -3.12897090e-01, -2.58666276e-01],
       [-9.75304830e-01, -1.67384754e+00, -5.58617754e-02],
       [-9.75304830e-01, -9.93372315e-01, -7.51191491e-01],
       [ 1.02532046e+00,  2.70367388e-01,  4.94607583e-01],
       [-9.75304830e-01, -1.18475597e-01, -1.06988428e+00],
       [ 1.02532046e+00, -1.09058306e+00,  5.81523798e-01],
       [ 1.02532046e+00,  7.59458956e-02, -8.09135634e-01],
       [ 1.02532046e+00, -9.93372315e-01,  1.53760216e+00],
       [-9.75304830e-01, -7.01740076e-01,  1.39274180e+00],
       [ 1.02532046e+00, -1.28500455e+00,  4.94607583e-01],
       [-9.75304830e-01, -3.12897090e-01,  3.10544391e-02],
       [ 1.02532046e+00, -1.18475597e-01,  2.08236764e-03],
       [ 1.02532046e+00, -3.12897090e-01, -8.96051849e-01],
       [ 1.02532046e+00,  8.53631867e-01, -1.35960499e+00],
       [-9.75304830e-01, -3.12897090e-01,  2.23293187e+00],
       [-9.75304830e-01,  9.50842613e-01,  1.97218323e+00],
       [ 1.02532046e+00, -1.18779381e+00,  4.65635512e-01],
       [ 1.02532046e+00, -1.28500455e+00,  2.62831011e-01],
       [-9.75304830e-01,  1.33968560e+00,  1.97218323e+00],
       [ 1.02532046e+00,  1.24247485e+00, -1.35960499e+00],
       [-9.75304830e-01, -3.12897090e-01, -2.87638347e-01],
       [-9.75304830e-01, -5.07318583e-01,  1.24788144e+00],
       [ 1.02532046e+00, -7.98950822e-01,  1.07404901e+00],
       [ 1.02532046e+00,  9.50842613e-01, -1.06988428e+00],
       [-9.75304830e-01,  2.70367388e-01,  2.91803083e-01],
       [-9.75304830e-01,  9.50842613e-01,  7.55356227e-01],
       [ 1.02532046e+00, -7.01740076e-01, -1.50446535e+00],
       [-9.75304830e-01, -7.01740076e-01,  3.10544391e-02],
       [ 1.02532046e+00,  4.64788881e-01,  1.71143459e+00],
       [-9.75304830e-01,  2.02016082e+00,  1.75914797e-01],
       [-9.75304830e-01, -1.96547978e+00, -7.51191491e-01],
       [ 1.02532046e+00, -2.15686344e-01,  1.39274180e+00],
       [-9.75304830e-01,  3.67578135e-01,  5.81523798e-01],
       [-9.75304830e-01,  8.53631867e-01, -1.15680049e+00],
       [-9.75304830e-01, -1.18779381e+00, -7.80163563e-01],
       [ 1.02532046e+00,  1.73156642e-01,  2.33858940e-01],
       [ 1.02532046e+00,  7.56421121e-01, -3.16610419e-01],
       [-9.75304830e-01,  2.02016082e+00, -8.09135634e-01],
       [-9.75304830e-01,  7.56421121e-01,  1.17970654e-01],
       [ 1.02532046e+00, -3.12897090e-01,  6.10495869e-01],
       [-9.75304830e-01, -9.93372315e-01, -3.16610419e-01],
       [ 1.02532046e+00,  1.73156642e-01, -3.74554562e-01],
       [ 1.02532046e+00,  2.02016082e+00,  2.11704359e+00],
       [-9.75304830e-01,  1.82573933e+00, -1.27268878e+00],
       [-9.75304830e-01,  1.33968560e+00, -9.25023920e-01],
       [-9.75304830e-01,  8.53631867e-01,  1.24788144e+00],
       [-9.75304830e-01,  1.43689635e+00,  2.11704359e+00],
       [ 1.02532046e+00, -3.12897090e-01, -1.24371671e+00],
       [-9.75304830e-01,  1.92295008e+00,  9.00216584e-01],
       [-9.75304830e-01,  6.59210374e-01, -7.22219420e-01],
       [-9.75304830e-01, -1.47942605e+00,  3.49747226e-01],
       [ 1.02532046e+00,  7.56421121e-01, -1.35960499e+00],
       [ 1.02532046e+00,  3.67578135e-01, -1.42777990e-01],
       [-9.75304830e-01, -9.93372315e-01,  4.07691369e-01],
       [ 1.02532046e+00, -2.12648508e-02, -3.16610419e-01],
       [-9.75304830e-01, -1.18779381e+00,  4.07691369e-01],
       [-9.75304830e-01, -8.96161568e-01, -1.21474464e+00],
       [-9.75304830e-01, -1.18475597e-01,  3.10544391e-02],
       [-9.75304830e-01, -1.57663679e+00, -4.32498705e-01],
       [-9.75304830e-01,  9.50842613e-01, -1.01194013e+00],
       [ 1.02532046e+00,  1.04805336e+00, -1.21474464e+00],
       [-9.75304830e-01, -2.12648508e-02, -1.42777990e-01],
       [-9.75304830e-01, -1.09058306e+00, -1.53343742e+00],
       [ 1.02532046e+00,  7.56421121e-01, -1.21474464e+00],
       [ 1.02532046e+00,  9.50842613e-01,  2.05909944e+00],
       [-9.75304830e-01, -1.18779381e+00, -1.53343742e+00],
       [-9.75304830e-01, -3.12897090e-01,  7.84328298e-01],
       [-9.75304830e-01,  7.59458956e-02, -3.16610419e-01],
       [-9.75304830e-01, -1.38221530e+00, -1.24371671e+00],
       [ 1.02532046e+00, -6.04529329e-01, -1.50446535e+00],
       [ 1.02532046e+00,  7.56421121e-01,  5.23579655e-01],
       [ 1.02532046e+00, -3.12897090e-01, -3.45582490e-01],
       [ 1.02532046e+00,  1.72852858e+00, -2.87638347e-01],
       [ 1.02532046e+00,  8.53631867e-01, -1.04091221e+00],
       [-9.75304830e-01,  1.73156642e-01,  6.00265106e-02],
       [ 1.02532046e+00, -6.04529329e-01,  8.71244512e-01],
       [-9.75304830e-01, -1.86826903e+00, -1.41754914e+00],
       [ 1.02532046e+00, -1.28500455e+00,  5.81523798e-01],
       [ 1.02532046e+00, -3.12897090e-01,  5.23579655e-01],
       [ 1.02532046e+00, -9.93372315e-01, -1.09885635e+00],
       [-9.75304830e-01,  1.14526411e+00, -1.44652121e+00],
       [ 1.02532046e+00,  1.73156642e-01, -3.16610419e-01],
       [-9.75304830e-01,  1.14526411e+00, -7.51191491e-01],
       [ 1.02532046e+00, -3.12897090e-01,  6.00265106e-02],
       [-9.75304830e-01,  1.73156642e-01,  2.08807152e+00],
       [-9.75304830e-01,  7.56421121e-01, -1.09885635e+00],
       [-9.75304830e-01,  7.59458956e-02,  3.10544391e-02],
       [ 1.02532046e+00, -1.77105829e+00,  1.17970654e-01],
       [ 1.02532046e+00, -8.96161568e-01,  1.46942725e-01],
       [ 1.02532046e+00, -7.01740076e-01,  1.75914797e-01],
       [ 1.02532046e+00,  8.53631867e-01, -1.30166085e+00],
       [ 1.02532046e+00,  1.73156642e-01, -2.58666276e-01],
       [ 1.02532046e+00, -4.10107836e-01,  1.21890937e+00],
       [-9.75304830e-01, -2.12648508e-02,  2.91803083e-01],
       [-9.75304830e-01,  3.67578135e-01,  1.46942725e-01],
       [-9.75304830e-01,  8.53631867e-01, -6.64275277e-01],
       [-9.75304830e-01,  7.59458956e-02,  1.46942725e-01],
       [ 1.02532046e+00, -1.86826903e+00, -1.30166085e+00],
       [-9.75304830e-01, -1.18475597e-01,  2.91803083e-01],
       [ 1.02532046e+00, -2.15686344e-01, -2.87638347e-01],
       [ 1.02532046e+00,  2.70367388e-01, -5.19414919e-01],
       [ 1.02532046e+00, -2.15686344e-01,  1.59554630e+00],
       [-9.75304830e-01,  9.50842613e-01, -1.18577256e+00],
       [-9.75304830e-01, -2.15686344e-01,  1.62451837e+00],
       [-9.75304830e-01,  1.24247485e+00,  1.85629494e+00],
       [-9.75304830e-01, -1.09058306e+00, -3.74554562e-01],
       [ 1.02532046e+00, -2.12648508e-02,  3.10544391e-02],
       [-9.75304830e-01,  7.59458956e-02, -2.58666276e-01],
       [-9.75304830e-01, -1.57663679e+00, -1.24371671e+00],
       [-9.75304830e-01, -5.07318583e-01, -2.87638347e-01],
       [ 1.02532046e+00,  9.50842613e-01,  1.17970654e-01],
       [-9.75304830e-01,  1.92295008e+00, -1.35960499e+00],
       [ 1.02532046e+00,  1.43689635e+00,  6.00265106e-02],
       [-9.75304830e-01, -6.04529329e-01,  1.36376973e+00],
       [ 1.02532046e+00,  1.53410709e+00,  2.08236764e-03],
       [ 1.02532046e+00, -7.98950822e-01,  2.91803083e-01],
       [-9.75304830e-01,  1.92295008e+00,  7.26384155e-01],
       [-9.75304830e-01, -1.18779381e+00, -5.19414919e-01],
       [ 1.02532046e+00,  6.59210374e-01,  2.62831011e-01],
       [ 1.02532046e+00, -1.38221530e+00, -4.32498705e-01],
       [ 1.02532046e+00,  1.73156642e-01,  1.46942725e-01],
       [-9.75304830e-01, -5.07318583e-01, -1.21474464e+00],
       [-9.75304830e-01,  5.61999628e-01,  2.00115530e+00],
       [ 1.02532046e+00, -1.57663679e+00, -1.50446535e+00],
       [-9.75304830e-01, -5.07318583e-01, -5.48386991e-01],
       [-9.75304830e-01,  4.64788881e-01,  1.82732287e+00],
       [-9.75304830e-01, -1.38221530e+00, -1.09885635e+00],
       [-9.75304830e-01,  7.56421121e-01, -1.38857706e+00],
       [ 1.02532046e+00, -3.12897090e-01, -4.32498705e-01],
       [-9.75304830e-01,  1.53410709e+00,  9.87132798e-01],
       [-9.75304830e-01,  9.50842613e-01,  1.42171387e+00],
       [ 1.02532046e+00, -3.12897090e-01, -4.90442848e-01],
       [ 1.02532046e+00, -1.18475597e-01,  2.14601566e+00],
       [-9.75304830e-01, -1.47942605e+00, -1.13805918e-01],
       [-9.75304830e-01, -1.18475597e-01,  1.94321116e+00],
       [ 1.02532046e+00, -7.01740076e-01, -3.45582490e-01],
       [-9.75304830e-01, -5.07318583e-01, -8.38107706e-01],
       [-9.75304830e-01,  6.59210374e-01, -1.38857706e+00],
       [ 1.02532046e+00, -7.98950822e-01, -1.59138156e+00],
       [ 1.02532046e+00, -1.86826903e+00, -1.47549328e+00],
       [ 1.02532046e+00,  1.04805336e+00,  1.17970654e-01],
       [ 1.02532046e+00,  7.59458956e-02,  1.50863009e+00],
       [ 1.02532046e+00, -3.12897090e-01,  8.89985821e-02],
       [ 1.02532046e+00,  7.59458956e-02,  3.10544391e-02],
       [ 1.02532046e+00, -1.38221530e+00, -1.35960499e+00],
       [-9.75304830e-01,  2.70367388e-01,  6.00265106e-02],
       [-9.75304830e-01, -8.96161568e-01,  3.78719297e-01],
       [-9.75304830e-01,  1.53410709e+00, -1.27268878e+00],
       [-9.75304830e-01, -3.12897090e-01, -7.51191491e-01],
       [ 1.02532046e+00, -1.18475597e-01,  1.46942725e-01],
       [-9.75304830e-01, -8.96161568e-01, -6.64275277e-01],
       [-9.75304830e-01, -7.01740076e-01, -5.58617754e-02],
       [ 1.02532046e+00,  3.67578135e-01, -4.61470776e-01],
       [ 1.02532046e+00, -7.98950822e-01,  1.88526701e+00],
       [-9.75304830e-01,  1.33968560e+00,  1.27685351e+00],
       [-9.75304830e-01,  1.14526411e+00, -9.82968063e-01],
       [ 1.02532046e+00,  1.72852858e+00,  1.82732287e+00],
       [ 1.02532046e+00, -8.96161568e-01, -2.58666276e-01],
       [ 1.02532046e+00, -7.98950822e-01,  5.52551726e-01],
       [ 1.02532046e+00, -1.18779381e+00, -1.56240949e+00],
       [ 1.02532046e+00, -5.07318583e-01, -1.12782842e+00],
       [-9.75304830e-01,  2.70367388e-01,  6.00265106e-02],
       [ 1.02532046e+00, -2.15686344e-01, -1.06988428e+00],
       [-9.75304830e-01,  1.63131784e+00,  1.59554630e+00],
       [-9.75304830e-01,  9.50842613e-01,  1.76937873e+00],
       [-9.75304830e-01,  2.70367388e-01,  3.10544391e-02],
       [-9.75304830e-01, -7.98950822e-01, -2.29694204e-01],
       [ 1.02532046e+00, -1.18475597e-01,  6.00265106e-02],
       [-9.75304830e-01,  2.70367388e-01, -2.00722133e-01],
       [-9.75304830e-01,  1.92295008e+00, -6.64275277e-01],
       [-9.75304830e-01, -7.98950822e-01,  1.33479766e+00],
       [ 1.02532046e+00, -1.77105829e+00, -6.06331134e-01],
       [ 1.02532046e+00, -1.18475597e-01,  1.17970654e-01],
       [ 1.02532046e+00,  2.70367388e-01, -3.16610419e-01],
       [ 1.02532046e+00,  1.04805336e+00,  5.52551726e-01],
       [ 1.02532046e+00, -9.93372315e-01,  2.62831011e-01],
       [-9.75304830e-01,  1.43689635e+00,  3.49747226e-01],
       [ 1.02532046e+00,  1.73156642e-01, -3.74554562e-01],
       [ 1.02532046e+00,  2.11737157e+00, -1.04091221e+00],
       [ 1.02532046e+00, -3.12897090e-01,  1.10302108e+00],
       [ 1.02532046e+00, -1.67384754e+00,  6.00265106e-02],
       [ 1.02532046e+00, -2.12648508e-02,  3.10544391e-02],
       [ 1.02532046e+00,  7.59458956e-02,  1.04507694e+00],
       [-9.75304830e-01, -1.18475597e-01, -3.74554562e-01],
       [-9.75304830e-01, -1.18779381e+00,  6.00265106e-02],
       [-9.75304830e-01, -3.12897090e-01, -1.35960499e+00],
       [-9.75304830e-01,  1.53410709e+00,  1.10302108e+00],
       [ 1.02532046e+00, -7.98950822e-01, -1.53343742e+00],
       [ 1.02532046e+00,  7.59458956e-02,  1.85629494e+00],
       [ 1.02532046e+00, -8.96161568e-01, -7.80163563e-01],
       [ 1.02532046e+00, -5.07318583e-01, -7.80163563e-01],
       [ 1.02532046e+00, -3.12897090e-01, -9.25023920e-01],
       [ 1.02532046e+00,  2.70367388e-01, -7.22219420e-01],
       [-9.75304830e-01,  2.70367388e-01,  6.00265106e-02],
       [-9.75304830e-01,  7.59458956e-02,  1.85629494e+00],
       [-9.75304830e-01, -1.09058306e+00,  1.94321116e+00],
       [-9.75304830e-01, -1.67384754e+00, -1.56240949e+00],
       [ 1.02532046e+00, -1.18779381e+00, -1.09885635e+00],
       [ 1.02532046e+00, -7.01740076e-01, -1.13805918e-01],
       [-9.75304830e-01,  7.59458956e-02,  8.89985821e-02],
       [ 1.02532046e+00,  2.70367388e-01,  2.62831011e-01],
       [-9.75304830e-01,  8.53631867e-01, -5.77359062e-01],
       [-9.75304830e-01,  2.70367388e-01, -1.15680049e+00],
       [-9.75304830e-01, -1.18475597e-01,  6.68440012e-01],
       [-9.75304830e-01,  2.11737157e+00, -6.93247348e-01],
       [ 1.02532046e+00, -1.28500455e+00, -1.38857706e+00],
       [-9.75304830e-01, -9.93372315e-01, -9.53995992e-01],
       [-9.75304830e-01, -2.12648508e-02, -4.32498705e-01],
       [-9.75304830e-01, -2.15686344e-01, -4.61470776e-01],
       [-9.75304830e-01, -1.77105829e+00, -9.82968063e-01],
       [-9.75304830e-01,  1.72852858e+00,  9.87132798e-01],
       [ 1.02532046e+00,  1.73156642e-01, -3.74554562e-01],
       [-9.75304830e-01,  3.67578135e-01,  1.10302108e+00],
       [-9.75304830e-01, -1.77105829e+00, -1.35960499e+00],
       [ 1.02532046e+00,  1.73156642e-01, -1.42777990e-01],
       [ 1.02532046e+00,  8.53631867e-01, -1.44652121e+00],
       [-9.75304830e-01, -1.96547978e+00,  4.65635512e-01],
       [ 1.02532046e+00, -3.12897090e-01,  2.62831011e-01],
       [-9.75304830e-01,  1.82573933e+00, -1.06988428e+00],
       [-9.75304830e-01, -4.10107836e-01,  6.00265106e-02],
       [-9.75304830e-01,  1.04805336e+00, -8.96051849e-01],
       [-9.75304830e-01, -1.09058306e+00, -1.12782842e+00],
       [ 1.02532046e+00, -1.86826903e+00,  2.08236764e-03],
       [-9.75304830e-01,  7.59458956e-02,  2.62831011e-01],
       [ 1.02532046e+00, -1.18779381e+00,  3.20775154e-01],
       [ 1.02532046e+00, -1.28500455e+00,  2.91803083e-01],
       [-9.75304830e-01, -9.93372315e-01,  4.36663440e-01],
       [ 1.02532046e+00,  1.63131784e+00, -8.96051849e-01],
       [-9.75304830e-01,  1.14526411e+00,  5.23579655e-01],
       [ 1.02532046e+00,  1.04805336e+00,  5.23579655e-01],
       [ 1.02532046e+00,  1.33968560e+00,  2.31984809e+00],
       [-9.75304830e-01, -3.12897090e-01, -1.42777990e-01],
       [ 1.02532046e+00,  3.67578135e-01, -4.61470776e-01],
       [ 1.02532046e+00, -4.10107836e-01, -7.80163563e-01],
       [ 1.02532046e+00, -1.18475597e-01, -5.19414919e-01],
       [-9.75304830e-01,  9.50842613e-01, -1.15680049e+00],
       [ 1.02532046e+00, -8.96161568e-01, -7.80163563e-01],
       [ 1.02532046e+00, -2.15686344e-01, -5.19414919e-01],
       [-9.75304830e-01, -1.09058306e+00, -4.61470776e-01],
       [-9.75304830e-01, -1.18779381e+00,  1.39274180e+00]])

In [17]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
y_pred = lr.predict(x_test)

TypeError: float() argument must be a string or a number, not 'StandardScaler'